default: &default
  adapter: mysql2
  reconnect: false
  pool: 5
  username: root
  password: ""
  host: localhost

development:
  database: fx_dev
  <<: *default

production:
  adapter: mysql2
  database: fx
  host: localhost
  username: root
  password: Yuukoudb321
  encoding: utf8
  pool: 30

test:
  adapter: mysql2
  database: fx_test
  host: localhost
  username: root
  password: 123456
  encoding: utf8

core:
  development:
    adapter: mysql2
    database: hzb_dev
    host: localhost
    username: root
    password: ""
    encoding: utf8
  production:
    adapter: mysql2
    database: hzb
    host: localhost
    username: root
    password: ""
    encoding: utf8
    pool: 30
