development: &default
  qiniu_fx: "hzb-fx"
  qiniu_fx_url: "http://7xu0y5.com1.z0.glb.clouddn.com/"
  qiniu_fx_domain: "7xu0y5.com1.z0.glb.clouddn.com/"
  qiniu: "hzb"
  qiniu_domain: "7xi8qz.com1.z0.glb.clouddn.com/"
  qiniu_access_key: "6sY85c6f3OTviHNVSLZJxiTs194XaRoOJl5hUf1N"
  qiniu_secret_key: "JVutfl_di00jepNuNeviyfv5X5qY0GVy4jm9ly1v"
  main_host: "http://beta.yuukuo.com"
  domain: "http://localhost:3000"
  secret_key_base: ab839b8a479e28bc64cd3f40cdb9681f671297774abdcb612f7ce57f35e6c65be9f30405b4a1f4aab25d65fe701569a8d1cb1e40340cb6c501ff8e8b631ecfd2

test:
  <<: *default
  secret_key_base: 968f4abb9bcf8537a32ca4edf02b27b9f814ba85017af25dd41ae4c0259d6be9f34fc1aa661f9a13542b8293c559be73f58fb601d5ec0d514509a26d37753b1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  main_host: "http://beta.yuukuo.com"
  domain: "http://fx.yuukuo.com"
  qiniu_domain: "7xi8qz.com1.z0.glb.clouddn.com/"
  secret_key_base: ae0a8c74b4509ea29cd1347f8fec3a93ee16e5337f3a9529b7b2c06e307f5e64b8c3f09f31a87adf22b1ab354b3be10fb70e24a3dbcc88f53491be3a3b5f59c5