# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: true
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency: 25
:timeout: 30
:queues:
  - [fx_often, 7]
  - [fx_default, 5]
  - [fx_seldom, 3]
  - [fx_mailer, 3]
  - [fx_notification, 3]
  - [fx_sms, 5]
  - [fx_jpush, 5]
  - [fx_count, 3]
